#!/bin/bash

# postinstall script for debian linux family
cat << EOF > /etc/rc2.d/S99vm_coordinator
/tmp/vm_coordinator/controllers/vm_coordinator_server.rb
EOF

chmod +x /etc/rc2.d/S99vm_coordinator
