#!/bin/bash

## substitute (if necessary) oneapps chef script
ONE_DIR=/etc/one-context.d
CHEF=$ONE_DIR/99-one-chef

rm -rf $CHEF
# ensure that directory exists
mkdir -p $ONE_DIR
ln -s /tmp/vm_coordinator/bin/99-one-chef $CHEF

## postinstall script for debian linux family
VM_COORDINATOR=/etc/rc2.d/S99vm_coordinator
cat << EOF > $VM_COORDINATOR
/tmp/vm_coordinator/controllers/vm_coordinator_server.rb
EOF

chmod +x $VM_COORDINATOR
