port: <%= ENV['ENDPOINT_PORT'] || 33331 %>

redis:
  host: <%= ENV['REDIS_HOST'] || '127.0.0.1' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>

amqp:
  host: <%= ENV['AMQP_HOST'] || '127.0.0.1' %>
  port: <%= ENV['AMQP_PORT'] || 5672 %>
  offers_exchange_name: <%= ENV['AMQP_OFFERS_EXCHANGE_NAME'] || 'default.offers_exchange.fanout' %>
  offers_routing_key: <%= ENV['AMQP_OFFERS_ROUTING_KEY'] || 'offers.routing_key' %>