broker_id: sap-broker-1
port: 65401

amqp:
  host: 192.168.0.12
  port: 5672
  offers_select_interval: 6

# This is broker-id in the amqp sense.
# Should be unique; otherwise there is an overhead with the amount
# of messages being received by brokers
  offers_routing_key: offers.sap_broker_1
  offers_exchange_name: default.offers_exchange.fanout

  autoscaling_queue_name: scaling.sap_broker_1

resource_mapping:
  strategy: flat
  offers_wait_interval: 10

### Endpoint-specific configuration file
# Database
development:
  database: ':memory:'
  database-log-level: info
test:
  database: ':memory:'
  database-log-level: info

