ruby '1.8.7'
source 'https://rubygems.org'

gem 'sinatra', :require => 'sinatra/base'
gem 'json'
gem 'redis'
gem 'amqp'
gem 'data_mapper'
gem 'dm-redis-adapter'

group :development do
  gem 'rspec'
  gem 'rack-test'
  gem 'sinatra-contrib'
  gem 'guard-rspec'
end
