
amqp:
  host: 192.168.0.12
  offers_exchange_name: default.offers_exchange.fanout
  controller_routing_key: sap-cloud-controller-1

pricing_mapping:
  strategy: flat
  
  flat:
    stack:
      java: 50
      mysql: 51
      ruby: 49

