## CONTROLLER SETTINGS
scheduler:
  test:
    interval: '5s'

  development:
    interval: '1m'


## CLOUD PROVIDER SETTINGS
cloud_provider_name:  opennebula

# store ids of opennebula resources
mappings:
  opennebula:
    stacks:
      java:
        master: 7
        slave:  7

endpoints:
  development:
    opennebula:
      username: oneadmin
      password: password
      endpoints:
                        opennebula: http://one:2633/RPC2
                        appflow: http://one:2474
      monitoring_keys:
                        - CPU
  test:
    opennebula:
      username: bolek
      password: lolek
      endpoints:
                        opennebula: http://cloud.com:2633/RPC2
                        appflow: http://cloud.com:2474
      monitoring_keys:
                        - CPU
                        - MEMORY
                        - NET_RX
