## CONTROLLER SETTINGS
scheduler:
  test:
    interval: '5s'

  development:
    interval: '1m'


## CLOUD PROVIDER SETTINGS
cloud_provider_name:  opennebula

# store ids of opennebula resources
mappings:
  opennebula:
    stacks:
      java:
        master: 4
        slave:  5

endpoints:
  development:
    opennebula:
      username: oneadmin
      password: 8425350dac7d9e85eab2854618639cde
      endpoints:
                        opennebula: http://192.168.0.32:2633/RPC2
                        appflow: http://192.168.0.32:2474
      monitoring_keys:
                        - CPU
      timeout:  5
      retries:  5
      sleep:    30

  test:
    opennebula:
      username: bolek
      password: lolek
      endpoints:
                        opennebula: http://my.domain.cloud.test.com:2633/RPC2
                        appflow: http://my.domain.cloud.test.com:2474
      monitoring_keys:
                        - CPU
                        - MEMORY
                        - NET_RX
      capacity:
                        cpu: 100
                        memory: 1000
      timeout:  5
      retries:  3
      sleep:    2
