endpoint:
  host: <%= ENV['CLIENT_HOST'] || '127.0.0.1' %>
  port: <%= ENV['CLIENT_PORT'] || 4567 %>

redis:
  host: <%= ENV['REDIS_HOST'] || '127.0.0.1' %>
  port: <%= ENV['REDIS_PORT'] || 6381 %>

cloud_broker:
  host: <%= ENV['CLOUD_BROKER_HOST'] || '127.0.0.1' %>
  port: <%= ENV['CLOUD_BROKER_PORT'] || 33331 %>
