# This test case configuration

amqp:
  host: 192.168.0.12

cloud_broker:
  id: sap-broker
  offers_exchange_name: fanout
  offers_routing_key: offers_rk
  autoscaling_queue_name: scaling
  host: 127.0.0.1
  port: 46712

cloud_controller_1:
  controller_routing_key: sap-cc-1
  frontend: 192.168.0.32
  java_price: 50

cloud_controller_2:
  controller_routing_key: sap-cc-2
  frontend: 192.168.0.36
  java_price: 60

